---
title: "airline_delays_main"
author: "Jiawei Li"
date: "10/11/2021"
output: html_document
---

```{r load pkgs, message = FALSE}
library(tidyverse)
library(lubridate)
library(GGally)
library(ggplot2)
library(corrplot)
library(rhdf5)
library(gtools)
library(scales)
library(rstanarm)
library(brms)
library(HBglm)
library(sfsmisc)
library("rprojroot")
root <- has_file("README.md")$make_fix_file()
set1 <- RColorBrewer::brewer.pal(7, "Set1")
```

```{r load_and_clean_data}
library(nycflights13)
data(flights)
flights <- flights[complete.cases(flights), ] %>% 
  mutate(date = ISOdate(year, month, day), DayOfWeek = wday(date), 
         Arr_delay = sapply(arr_delay - 15, function(x) ceiling(max(x, 0))))
y_nyc <- permute(flights$Arr_delay)
N <- length(y_nyc)
```

```{r load_functions}
source(root("spc/codes", "utils.r"))

```

## 1. Conjugate geometric model
```{r}
## I. geometric model: y ~ Geo(p)
##                     p ~ Beta(a0, b0)
# rerun 'run_experiment_geom' for N_obs = 500, 1000, 2000, 3000, 5000

source(root("spc/experiments/airlines","airlines_funs_geom.R"))
run_experiment_geom(N_obs = 500, data = y_nyc, discr_name = "success_rate", 
                    results_path = "nyc_airline_delays_results_geom.rda", R = 500)
run_experiment_geom(N_obs = 500, data = y_nyc, discr_name = "mse", 
                    results_path = "nyc_airline_delays_results_geom.rda", R = 500)
y_rep_geom <-  generate_yreps_given_obs(y_nyc, R = 1000, N)


load("nyc_airline_delays_results_geom.rda")
results <- results %>% filter(method %in% c("PPC","single 0.5-SPC", 
                                            "divided 0.5-SPC, k = N^0.49",
                                            "divided 0.5-SPC, k = N^0.39"))
power_plot_airlines(results, discr = "success_rate")

```


## 2. Negative binomial GLM

model_formula = @formula((ArrDelay-15)~sin(Month/12)+cos(Month/12) + sin(DayOfWeek/7) + cos(DayOfWeek/7) + Distance)
```{r}
## load functions
source(root("spc/experiments/airlines","airlines_funs_negbinGLM.R"))
```

```{r}

run_experiment_negbin(flights, discr_name = "success_rate", result_path = "nyc_airline_delays_results_negbin.rda", R = 1000)


divide_data_glm <- function(data, rate, interpolation){
  N <- length(data)
  N_sub <- floor(N^(1-rate))
  K <- floor(N^(rate))
  Xsubs <- list()
  if(interpolation){
    data$intid <- c(rep(1:K, N_sub + 1), rep(NA,N%%K))
    data <- data[1:(K*(N_sub + 1)), ]
        for(k in 1:K){
          Xsubs[[k]] <- data[data$intid == k, ]
        }
  }else if(!interpolation){
    for(k in 1:(K-1)){
    Xsubs[[k]] <- data[((k-1) * N_sub + 1) : (k * N_sub), ]
    }
    Xsubs[[K]] <- data[-(1 : ((K-1) * N_sub)), ]
  }else{
    stop("Error: missing interpolation type")
  }
  return(Xsubs)
}

```

- Plot histogram comparison between data distribution, posterior predictive distribution under geometric and negative binomial GLM models.
```{r}
y_rep_nb <-  matrix(generate_yreps_given_obs(data_obs = flights, 
                                             data_new = flights, R = 1000), R, N)
y_rep_nb <- apply(y_rep_nb[-(1:1000)], 2, mean)
plot_hist_comparison(flights$Arr_delay, y_rep_geom, y_rep_nb)
```
